
version: 2.1

workflows:
  build_deploy:
    jobs:
      - tox_test:
          version: "3.6.1"
          tox_version: py36
      - deploy:
          filters:
            tags:
              only: /v.*/

jobs:
  tox_test:
    parameters:
      version:
        type: string
        default: latest
      tox_version:
        type: string
        default: py37
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo "<< parameters.tox_version >>"
  deploy:
    requires:
      - tox_test
    filters:
      tags:
        only: /^v.*/
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            echo "deploy"