
version: 2
jobs:
  tox_py2:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo "tox_py2"

workflows:
  version: 2
  build_deploy:
    jobs:
      - tox_py2