
version: 2
jobs:
  tox_py2:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo "tox_py2"
  tox_py3:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: test
          command: |
            echo "tox_py3"
  deploy:
    requires:
      - tox_py2
      - tox_py3
    filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            echo "deploy"

workflows:
  version: 2
  build_deploy:
    jobs:
      - tox_py2
      - tox_py3
      - deploy